name: Auto Build Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure toolchains
      run: sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu- bc bison build-essential ccache curl flex git git-lfs gnupg gperf imagemagick libelf-dev liblz4-tool libncurses6 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev clang llvm

    - name: Build Kernel
      run: chmod -R 777 .
           make -j32 ARCH=arm64 SUBARCH=arm O=out CC="ccache clang" LD=aarch64-linux-gnu-ld CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=aarch64-linux-gnueabi- CROSS_COMPILE_ARM32=arm-linux-gnueabi- KCFLAGS="--sysroot=/usr/aarch64-linux-gnu -Wno-unused-but-set-variable -Wno-implicit-function-declaration -Wno-unused-variable -Wno-unused-function -Wno-unused-label" quiet=quiet_ evergo_defconfig
           make -j32 ARCH=arm64 SUBARCH=arm O=out CC="ccache clang" LD=aarch64-linux-gnu-ld CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=aarch64-linux-gnueabi- CROSS_COMPILE_ARM32=arm-linux-gnueabi- KCFLAGS="--sysroot=/usr/aarch64-linux-gnu -Wno-unused-but-set-variable -Wno-implicit-function-declaration -Wno-unused-variable -Wno-unused-function -Wno-unused-label" quiet=quiet_

    - name: Git AnyKernel3
      run: git clone https://github.com/osm0sis/AnyKernel3.git Anykernel3 --depth=1

    - name: Zip AnyKernel3.zip
      run: cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
           zip AnyKernel3.zip AnyKernel3.zip

    - name: Upload AnyKernel3.zip
      uses: actions/upload-artifact@v4
      with:
            name: AnyKernel3.zip
            path: AnyKernel3.zip
