name: Auto kernel build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ARM64 Toolchain
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            libc6-dev-arm64-cross

      - name: Build Kernel
        env:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
        run: |
          make -j$(nproc) O=out \
            CC="ccache clang" \
            LD=aarch64-linux-gnu-ld \
            CROSS_COMPILE_COMPAT=aarch64-linux-gnueabi- \
            KCFLAGS="--sysroot=/usr/aarch64-linux-gnu -Wno-unused-variable" \
            evergo_defconfig

          make -j$(nproc) O=out

      - name: Package Artifact
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          zip -r AnyKernel3.zip AnyKernel3/
